version: "3.7"

services:
  test-postgres-db:
    image: postgres:11
    container_name: test-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
    networks:
      - dagster

networks:
  dagster:
