apiVersion: v1
kind: Service
metadata:
    name: cassandra
    labels:
        app: calibraas
        type: storage
        subtype: cassandra
spec:
    type: ClusterIP
    selector:
        app: calibraas
        type: storage
        subtype: cassandra
    ports:
        - port: 9042
          targetPort: 9042
